version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  assignees:
  - ctrleverything
  ignore:
  - dependency-name: "@babel/core"
    versions:
    - 7.13.14
    - 7.13.15
