version: 2.1

orbs:
  node: circleci/node@4.5.1

jobs:
  build:  
    docker:
      - image: cimg/node:16.3
    steps:
      - checkout 
      - node/install-packages:
          pkg-manager: yarn
          override-ci-command: yarn install --immutable
      - run:
          name: Build with yarn + gulp
          command: yarn run gulp build

workflows:
  sample: 
    jobs:
      - build
